### ISSUE TITLE
Error about $sidebar-width SCSS variable in nuxt.js

### ISSUE THREAD

**Issue by bangtony** [creativetimofficial/vue-light-bootstrap-dashboard#21]
Dear team,

I am using vue-light-bootstrap-dashboard for nuxt.js v1.4.0 and got an error as below. Could you please help!

**Note:**
- I installed node-sass and sass-loader
 $ npm install --save-dev node-sass sass-loader
- In nuxt.config.js added the CSS resources:
css: [
  '~/assets/sass/light-bootstrap-dashboard.scss'
]

**Log error:**
 ```
ERROR  Failed to compile with 1 errors                                                                         11:44:45
 error  in ./assets/sass/light-bootstrap-dashboard.scss

Module build failed: Error: Lexical error on line 1. Unrecognized text.
100% - $sidebar-width
-------^
    at Parser.parseError (E:\nuxt\part3\node_modules\postcss-cssnext\node_modules\reduce-css-calc\dist\parser.js:160:21)
    at Object.parseError (E:\nuxt\part3\node_modules\postcss-cssnext\node_modules\reduce-css-calc\dist\parser.js:309:28) 
   at Object.next (E:\nuxt\part3\node_modules\postcss-cssnext\node_modules\reduce-css-calc\dist\parser.js:564:25)
    at Object.lex (E:\nuxt\part3\node_modules\postcss-cssnext\node_modules\reduce-css-calc\dist\parser.js:574:22)
    at Object.lex (E:\nuxt\part3\node_modules\postcss-cssnext\node_modules\reduce-css-calc\dist\parser.js:578:25)
    at lex (E:\nuxt\part3\node_modules\postcss-cssnext\node_modules\reduce-css-calc\dist\parser.js:196:27)
    at Parser.parse (E:\nuxt\part3\node_modules\postcss-cssnext\node_modules\reduce-css-calc\dist\parser.js:209:26)
    at E:\nuxt\part3\node_modules\postcss-cssnext\node_modules\reduce-css-calc\dist\index.js:35:30
    at walk (E:\nuxt\part3\node_modules\postcss-value-parser\lib\walk.js:15:13)
    at ValueParser.walk (E:\nuxt\part3\node_modules\postcss-value-parser\lib\index.js:18:5)
    at exports.default (E:\nuxt\part3\node_modules\postcss-cssnext\node_modules\reduce-css-calc\dist\index.js:29:51)
    at transformValue (E:\nuxt\part3\node_modules\postcss-cssnext\node_modules\postcss-calc\dist\lib\transform.js:24:45)
    at exports.default (E:\nuxt\part3\node_modules\postcss-cssnext\node_modules\postcss-calc\dist\lib\transform.js:54:100)
    at E:\nuxt\part3\node_modules\postcss-cssnext\node_modules\postcss-calc\dist\index.js:28:52
    at E:\nuxt\part3\node_modules\postcss\lib\container.js:144:26
    at Rule.each (E:\nuxt\part3\node_modules\postcss\lib\container.js:110:22)

 @ ./assets/sass/light-bootstrap-dashboard.scss 4:14-220 13:3-17:5 14:22-228
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr ./.nuxt/client.js
```

**Comment by nikchanda** [comment]
@bangtony  I just tried my first build and ran into the same error -- did you find an answer to this issue?

**Comment by bangtony** [comment]
@nikchanda 
I changed vue-light-bootstrap-dashboard as a plugin of nuxt.js as below:
1. Directory structure:
  --| plugins
  --|--|  LightBootstrapPlugin
  --|--|--| index.js
  --|--|--| globalDirectives.js
  --|--|--| globalComponents.js
  --|--|--| your file...
  --|--|  SidebarPlugin
  --|--|--| index.js
  --|--|--| SideBar.vue
  --|--|--| SidebarLink.vue

Content of LightBootstrapPlugin/index.js:
```
import VTooltip from 'v-tooltip'
// Notifications plugin
import Notifications from 'vue-notifyjs'
// A plugin file where you could register global components used across the app
import GlobalComponents from './globalComponents.js'
// A plugin file where you could register global directives
import GlobalDirectives from './globalDirectives.js'
// Sidebar on the right. Used as a local plugin in DashboardLayout.vue
import SideBar from '~/plugins/SidebarPlugin'

import Tab from '~/plugins/TabPlugin'

// asset imports
import 'bootstrap/dist/css/bootstrap.css'
import 'vue-notifyjs/themes/default.scss'
import '@/assets/sass/light-bootstrap-dashboard.scss'
import '@/assets/css/light-bootstrap-dashboard.css'

// library auto imports
import 'es6-promise/auto'

/**
 * This is the main Light Bootstrap Dashboard Vue plugin where dashboard related plugins are registerd.
 */
const LightBootstrapPlugin = {
  install (Vue) {
    Vue.use(GlobalComponents)
    Vue.use(GlobalDirectives)
    Vue.use(SideBar)
    Vue.use(Notifications)
    Vue.use(Tab)
    Vue.use(VTooltip)
  }
}

export default LightBootstrapPlugin
```

2. Import LightBootstrapPlugin and SidebarPlugin to nuxt.config.js:
 ```
 plugins: [
    '~/plugins/SidebarPlugin',
    '~/plugins/LightBootstrapPlugin',
  ]
```
