### ISSUE TITLE
[Bug] Project does not build

### ISSUE THREAD

**Issue by rcavaz** [creativetimofficial/vue-light-bootstrap-dashboard#81]
### Version
2.1.0

### Reproduction link
https://jsfiddle.net/

### Operating System
Ubuntu 22.04.1 LTS

### Device
Laptop

### Browser & Version
Google Chrome, Version 109.0.5414.74 (Official Build) (64-bit)

### Steps to reproduce
```sh
nvm use v19.4.0
unzip vue-light-bootstrap-dashboard-master.zip
cd vue-light-bootstrap-dashboard-master.zip
npm install
npm run dev
```

### What is expected?
It is expected to work out of the box

### What is actually happening?
Project fails to build, 40+ vulnerabilities are reported but "npm audit fix" nor "npm audit fix --force" fixes them.

Running "npm run dev" is unable to launch the application.
```
10% building 2/2 modules 0 activeError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/home/rcavaz/Downloads/vue-light-bootstrap-dashboard-master/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/rcavaz/Downloads/vue-light-bootstrap-dashboard-master/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/rcavaz/Downloads/vue-light-bootstrap-dashboard-master/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/rcavaz/Downloads/vue-light-bootstrap-dashboard-master/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/rcavaz/Downloads/vue-light-bootstrap-dashboard-master/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/rcavaz/Downloads/vue-light-bootstrap-dashboard-master/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/rcavaz/Downloads/vue-light-bootstrap-dashboard-master/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/rcavaz/Downloads/vue-light-bootstrap-dashboard-master/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/rcavaz/Downloads/vue-light-bootstrap-dashboard-master/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/rcavaz/Downloads/vue-light-bootstrap-dashboard-master/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/rcavaz/Downloads/vue-light-bootstrap-dashboard-master/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/rcavaz/Downloads/vue-light-bootstrap-dashboard-master/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/rcavaz/Downloads/vue-light-bootstrap-dashboard-master/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/rcavaz/Downloads/vue-light-bootstrap-dashboard-master/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
10% building 2/5 modules 3 active ...ode_modules/webpack-dev-server/client/index.js?http://localhostnode:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/home/rcavaz/Downloads/vue-light-bootstrap-dashboard-master/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/rcavaz/Downloads/vue-light-bootstrap-dashboard-master/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/rcavaz/Downloads/vue-light-bootstrap-dashboard-master/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/rcavaz/Downloads/vue-light-bootstrap-dashboard-master/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/rcavaz/Downloads/vue-light-bootstrap-dashboard-master/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/rcavaz/Downloads/vue-light-bootstrap-dashboard-master/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/rcavaz/Downloads/vue-light-bootstrap-dashboard-master/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/rcavaz/Downloads/vue-light-bootstrap-dashboard-master/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/rcavaz/Downloads/vue-light-bootstrap-dashboard-master/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/rcavaz/Downloads/vue-light-bootstrap-dashboard-master/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/rcavaz/Downloads/vue-light-bootstrap-dashboard-master/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v19.4.0
```

---

**Comment by pedroheavy** [comment]
did you find something?

**Comment by MazueraAlvaro** [comment]
This fork is ready to be merged to master and this bug is fixed.
https://github.com/maisamaf/vue-light-bootstrap-dashboard/tree/feature/v2.1.1
